FOREIGN_KEY_USER_ID = 'user.id'
INVESTED_AMOUNT_DEFAULT = 0
JWR_STRATEGY_LIFETIME = 3600
MIN_LENGTH_DESCRIPTION_PROJECT = 1
MIN_LENGTH_NAME_PROJECT = 1
MAX_LENGTH_NAME_PROJECT = 100
PASSWORD_MIN_LENGTH = 3
